displayName=RuneTags
author=1877
description=Quick-card profiles for player mentions and tags.
tags=1877,runetags,rune-tags,player,players,quick,card,profile,tags,tagging,mentions,chat,clan
version=1.0.0
plugins=com.runetags.RuneTagsPlugin
build=standard